KPI_DASHBOARD/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace KPI_DASHBOARD.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

KPI_DASHBOARD/Controllers/AnalystController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using KPI_DASHBOARD.Core.Data;
using KPI_DASHBOARD.Core.Business;
using PagedList;
using System.Linq;
using static KPI_DASHBOARD.Core.Business.Helper;
using KPI_DASHBOARD.Security;

namespace KPI_DASHBOARD.Controllers
{
    [AuthorizeRole((int)ApplicationRole.Analyst)]
    [OutputCache(NoStore = true, Duration = 0)]
    public class AnalystController : Controller
    {
        private IAnalystManager analystManager;

        public AnalystController()
        {
            analystManager = new AnalystManager();
        }

        public AnalystController(IAnalystManager _analystManager)
        {
            analystManager = _analystManager;
        }

        // GET: (System) Analyst
        public ActionResult Index(int? page, int? userID)
        {
            //int pageSize = 5;
            //int pageIndex = 1;
            //pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            //EMPLOYEE_LOGIN user = analystManager.FindUser(userID);
            //List<EMPLOYEE_LOGIN> list = new List<EMPLOYEE_LOGIN>();
            //list.Add(user);

            ViewBag.id = userID;

            return View();
        }

        // GET: (System) Analyst/Manage
        public ActionResult Manage(int? page)
        {
            int pageSize = 5;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            List<EMPLOYEE_LOGIN> userList = analystManager.GetUserList();
            return View(userList.ToPagedList(pageIndex, pageSize));
        }

        // GET: (System) Analyst/Create
        public ActionResult Create()
        {
            ViewBag.EMP_ROLE = new SelectList(analystManager.GetRoles(), "ROLE_ID", "ROLE_NAME");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EMP_LOG_USER_SYS_ID,EMP_LOG_PASSWORD,EMP_ROLE")] EMPLOYEE_LOGIN empDetails)
        {
            if (ModelState.IsValid)
            {
                analystManager.CreateUser(empDetails);
                return RedirectToAction("Manage");
            }

            ViewBag.EMP_ROLE = new SelectList(analystManager.GetRoles(), "ROLE_ID", "ROLE_NAME", empDetails.EMP_ROLE);
            return View(empDetails);
        }

        // GET: (System) Analyst/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE_LOGIN empDetails = analystManager.FindUser(id);
            if (empDetails == null)
            {
                return HttpNotFound();
            }
            return View(empDetails);
        }

        // GET: (System) Analyst/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE_LOGIN empDetails = analystManager.FindUser(id);
            if (empDetails == null)
            {
                return HttpNotFound();
            }
            ViewBag.EMP_ROLE = new SelectList(analystManager.GetRoles(), "ROLE_ID", "ROLE_NAME", empDetails.EMP_ROLE);
            return View(empDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EMP_LOG_USER_SYS_ID,EMP_LOG_PASSWORD,EMP_ROLE")] EMPLOYEE_LOGIN empDetails)
        {
            if (ModelState.IsValid)
            {
                analystManager.EditUser(empDetails);
                return RedirectToAction("Manage");
            }
            ViewBag.EMP_ROLE = new SelectList(analystManager.GetRoles(), "ROLE_ID", "ROLE_NAME", empDetails.EMP_ROLE);
            return View(empDetails);
        }

        // GET: (System) Analyst/Delete
        public ActionResult Delete(int? id, int? RoleId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //if (RoleId == (int)ApplicationRole.Analyst)
            //{
            //    return View("Error");
            //}
            EMPLOYEE_LOGIN empDetails = analystManager.FindUser(id);
            if (empDetails == null)
            {
                return HttpNotFound();
            }
            return View(empDetails);
        }

        // POST: (System) Analyst/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            analystManager.DeleteUser(id);
            return RedirectToAction("Manage");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                analystManager.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult HRMasterData()
        {
            return View();
        }

        public ActionResult Kenexa()
        {
            return View();
        }

        public ActionResult Terminations()
        {
            return View();
        }

        public ActionResult Absences()
        {
            return View();
        }
    }
}

KPI_DASHBOARD/Views/Analyst/Absences.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN
@{
    ViewBag.Title = "Absences";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/AnalystIndex.css">

<h2>Absences</h2>
<body>
    <!-- Sidebar -->
    <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
        <button onclick="w3_close()" class="w3-bar-item w3-large">&times;</button>
        <b class="w3-bar-item">Menu</b>
        <a href="@Url.Action("HRMasterData", "Analyst")" class="w3-bar-item w3-button">HR Master Data</a>
        <a href="@Url.Action("Kenexa", "Analyst")" class="w3-bar-item w3-button">Kenexa</a>
        <a href="@Url.Action("Absences", "Analyst")" class="w3-bar-item w3-button">Absences</a>
        <a href="@Url.Action("Terminations", "Analyst")" class="w3-bar-item w3-button">Terminations</a>

        <br />
        <a href="@Url.Action("Manage", "Analyst")" class="w3-bar-item w3-button">Manage Users</a>
    </div>

    <!-- Page Content -->
    <div class="w3-light-gray" style="border-radius:15px">
        <button class="w3-button w3-yellow w3-xlarge" style="border-radius:15px" onclick="w3_open()">☰</button>
        <div class='tableauPlaceholder' id='viz1510854594993' style="background-size:90%;width:90%;position:relative;margin-top:20px;"><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;2017Absences&#47;AbsencesAggregate&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='2017Absences&#47;AbsencesAggregate' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;2017Absences&#47;AbsencesAggregate&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>
        <script type='text/javascript'>                    var divElement = document.getElementById('viz1510854594993');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
    </div>

    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</body>

KPI_DASHBOARD/Views/Analyst/Create.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="margin-top:20px;">User Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EMP_LOG_USER_SYS_ID, "User System ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMP_LOG_USER_SYS_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMP_LOG_USER_SYS_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMP_LOG_PASSWORD, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMP_LOG_PASSWORD, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.EMP_LOG_PASSWORD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMP_ROLE, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EMP_ROLE", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMP_ROLE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Manage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KPI_DASHBOARD/Views/Analyst/Delete.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Confirm Deletion of Account</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            User System ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMP_LOG_USER_SYS_ID)
        </dd>

        <dt>
            Role
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER_ROLES.ROLE_NAME)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Manage")
        </div>
    }
</div>

KPI_DASHBOARD/Views/Analyst/Details.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>

    <h4 style="margin-top:20px;">User Account Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            User System ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMP_LOG_USER_SYS_ID)
        </dd>

        <dt>
            Role
        </dt>

        <dd>
            @Html.DisplayFor(model => model.USER_ROLES.ROLE_NAME)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EMP_LOG_USER_SYS_ID }) |
    @Html.ActionLink("Back to List", "Manage")
</p>

KPI_DASHBOARD/Views/Analyst/HRMasterData.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN
@{
    ViewBag.Title = "HRMasterData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/AnalystIndex.css">

<h2>HR Master Data</h2>
<body>
    <!-- Sidebar -->
    <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
        <button onclick="w3_close()" class="w3-bar-item w3-large">&times;</button>
        <b class="w3-bar-item">Menu</b>
        <a href="@Url.Action("HRMasterData", "Analyst")" class="w3-bar-item w3-button">HR Master Data</a>
        <a href="@Url.Action("Kenexa", "Analyst")" class="w3-bar-item w3-button">Kenexa</a>
        <a href="@Url.Action("Absences", "Analyst")" class="w3-bar-item w3-button">Absences</a>
        <a href="@Url.Action("Terminations", "Analyst")" class="w3-bar-item w3-button">Terminations</a>

        <br />
        <a href="@Url.Action("Manage", "Analyst")" class="w3-bar-item w3-button">Manage Users</a>
    </div>

    <!-- Page Content -->
    <div class="w3-light-gray" style="border-radius:15px">
        <button class="w3-button w3-yellow w3-xlarge" style="border-radius:15px" onclick="w3_open()">☰</button>
        <div class='tableauPlaceholder' id='viz1510811374436' style="background-size: 60%;width:60%;position:relative;margin-top:20px"><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;HR&#47;HR_57&#47;NationalityAgeGroup&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='HR_57&#47;NationalityAgeGroup' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;HR&#47;HR_57&#47;NationalityAgeGroup&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>
        <script type='text/javascript'>                    var divElement = document.getElementById('viz1510811374436');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
    </div>

    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</body>

KPI_DASHBOARD/Views/Analyst/Index.cshtml
<!-- @using PagedList.Mvc; -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/AnalystIndex.css">

<html>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <h2><b>Welcome!</b></h2>

        <!-- Sidebar -->
        <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
            <button onclick="w3_close()" class="w3-bar-item w3-large">&times;</button>
            <b class="w3-bar-item">Menu</b>
            <a href="@Url.Action("HRMasterData", "Analyst")" class="w3-bar-item w3-button">HR Master Data</a>
            <a href="@Url.Action("Kenexa", "Analyst")" class="w3-bar-item w3-button">Kenexa</a>
            <a href="@Url.Action("Absences", "Analyst")" class="w3-bar-item w3-button">Absences</a>
            <a href="@Url.Action("Terminations", "Analyst")" class="w3-bar-item w3-button">Terminations</a>

            <br />
            <a href="@Url.Action("Manage", "Analyst")" class="w3-bar-item w3-button">Manage Users</a>
        </div>

        <!-- Page Content -->
        <div class="w3-light-gray" style="border-radius:15px;">
            <button class="w3-button w3-yellow w3-xlarge" style="border-radius:15px"onclick="w3_open()">☰</button>
            <div class="w3-light-gray" style="text-align:center;padding-bottom:50px;" >
                <img src="~/Content/Images/person-placeholder.jpg" style="width:200px;height:200px;margin:auto;border-radius:50%;border:solid;border-color:darkgray;" />
                <p style="margin-top:30px;">
                    <h2 style="color:dimgray">Analyst</h2>
                </p>
            </div>
        </div>

        <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
        </script>
    </body>
</html>

KPI_DASHBOARD/Views/Analyst/Kenexa.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN
@{
    ViewBag.Title = "Kenexa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/AnalystIndex.css">

<h2>Kenexa</h2>
<body>
    <!-- Sidebar -->
    <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
        <button onclick="w3_close()" class="w3-bar-item w3-large">&times;</button>
        <b class="w3-bar-item">Menu</b>
        <a href="@Url.Action("HRMasterData", "Analyst")" class="w3-bar-item w3-button">HR Master Data</a>
        <a href="@Url.Action("Kenexa", "Analyst")" class="w3-bar-item w3-button">Kenexa</a>
        <a href="@Url.Action("Absences", "Analyst")" class="w3-bar-item w3-button">Absences</a>
        <a href="@Url.Action("Terminations", "Analyst")" class="w3-bar-item w3-button">Terminations</a>

        <br />
        <a href="@Url.Action("Manage", "Analyst")" class="w3-bar-item w3-button">Manage Users</a>
    </div>

    <!-- Page Content -->
    <div class="w3-light-gray" style="border-radius:15px">
        <button class="w3-button w3-yellow w3-xlarge" style="border-radius:15px" onclick="w3_open()">☰</button>
        <div class='tableauPlaceholder' id='viz1512627213209' style="background-size: 90%;width:90%;position:relative;margin-top:20px;"><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ke&#47;Kenexa&#47;NumberofHiresperOpening&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Kenexa&#47;NumberofHiresperOpening' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ke&#47;Kenexa&#47;NumberofHiresperOpening&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>
        <script type='text/javascript'>                    var divElement = document.getElementById('viz1512627213209');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
    </div>

    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</body>

KPI_DASHBOARD/Views/Analyst/Terminations.cshtml
@model KPI_DASHBOARD.Core.Data.EMPLOYEE_LOGIN
@{
    ViewBag.Title = "Terminations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/AnalystIndex.css">

<h2>Terminations</h2>
<body>
    <!-- Sidebar -->
    <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
        <button onclick="w3_close()" class="w3-bar-item w3-large">&times;</button>
        <b class="w3-bar-item">Menu</b>
        <a href="@Url.Action("HRMasterData", "Analyst")" class="w3-bar-item w3-button">HR Master Data</a>
        <a href="@Url.Action("Kenexa", "Analyst")" class="w3-bar-item w3-button">Kenexa</a>
        <a href="@Url.Action("Absences", "Analyst")" class="w3-bar-item w3-button">Absences</a>
        <a href="@Url.Action("Terminations", "Analyst")" class="w3-bar-item w3-button">Terminations</a>

        <br />
        <a href="@Url.Action("Manage", "Analyst")" class="w3-bar-item w3-button">Manage Users</a>
    </div>

    <!-- Page Content -->
    <div class="w3-light-gray" style="border-radius:15px">
        <button class="w3-button w3-yellow w3-xlarge" style="border-radius:15px" onclick="w3_open()">☰</button>
        <div class='tableauPlaceholder' id='viz1512628513884' style="background-size: 90%;width:90%;position:relative;margin-top:20px;"><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;2017Terminations&#47;JobTitle&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='2017Terminations&#47;JobTitle' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;2017Terminations&#47;JobTitle&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /></object></div>
        <script type='text/javascript'>                    var divElement = document.getElementById('viz1512628513884');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
    </div>
    
    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</body>