KPI_DASHBOARD/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using KPI_DASHBOARD.Core.Data;
using KPI_DASHBOARD.Core.Business;
using KPI_DASHBOARD.Security;
using PagedList;

namespace KPI_DASHBOARD.Controllers
{
    [AuthorizeRole((int)Helper.ApplicationRole.Manager)]
    [OutputCache(NoStore = true, Duration = 0)]
    public class ManagerController : Controller
    {
        // GET: Manager
        public ActionResult Index(int? page, int? userID)
        {
            ViewBag.id = userID;

            return View();
        }
    }
}

KPI_DASHBOARD/Controllers/TableauController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KPI_DASHBOARD.Controllers
{
    public class TableauController : Controller
    {
        public ActionResult HRMasterData()
        {
            return View();
        }

        public ActionResult Kenexa()
        {
            return View();
        }

        public ActionResult Terminations()
        {
            return View();
        }

        public ActionResult Absences()
        {
            return View();
        }
    }
}

KPI_DASHBOARD/Views/Manager/Index.cshtml
<!-- @using PagedList.Mvc; -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/AnalystIndex.css">

<html>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <h2><b>Welcome!</b></h2>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-bar-block w3-border-right" style="display:none" id="mySidebar">
        <button onclick="w3_close()" class="w3-bar-item w3-large">&times;</button>
        <b class="w3-bar-item">Menu</b>
        <a href="@Url.Action("HRMasterData", "Tableau")" class="w3-bar-item w3-button">HR Master Data</a>
        <a href="@Url.Action("Kenexa", "Tableau")" class="w3-bar-item w3-button">Kenexa</a>
        <a href="@Url.Action("Absences", "Tableau")" class="w3-bar-item w3-button">Absences</a>
        <a href="@Url.Action("Terminations", "Tableau")" class="w3-bar-item w3-button">Terminations</a>
    </div>

    <!-- Page Content -->
    <div class="w3-light-gray" style="border-radius:15px;">
        <button class="w3-button w3-yellow w3-xlarge" style="border-radius:15px" onclick="w3_open()">☰</button>
        <div class="w3-light-gray" style="text-align:center;padding-bottom:50px;">
            <img src="~/Content/Images/person-placeholder.jpg" style="width:200px;height:200px;margin:auto;border-radius:50%;border:solid;border-color:darkgray;" />
            <p style="margin-top:30px;">
                <h2 style="color:dimgray">Manager</h2>
            </p>
        </div>
    </div>

    <script>
        function w3_open() {
            document.getElementById("mySidebar").style.display = "block";
        }
        function w3_close() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
</body>
</html>